#!/usr/bin/env python3
"""Generate `docs/catalog.md` from a site's design inputs.

The component library documents itself as a side effect of existing. Hand-written
catalogues rot the moment someone is in a hurry, so this one is generated and the
pre-commit hook refuses a commit where it is stale.

**Why byte comparison rather than a checksum.** `--check` regenerates the
catalogue in memory and compares it to the committed file exactly. A stored hash
only proves the inputs are unchanged; comparing output proves the *document* is
what the current code and inputs produce, which is the thing being claimed. It
also means the generator must be deterministic — so nothing here embeds a
timestamp, a path outside the repo, or an iteration order that depends on a set.

**Why the example site.** Real sites live in the gitignored private layer, so
their catalogue cannot be committed and would leak facts if it were. The
committed catalogue documents `sites/example/`, which is fictional on purpose.

    buildsmith docs                    # regenerate docs/catalog.md
    buildsmith docs --check            # non-zero if it is stale
    buildsmith docs --site other --out -   # some other site, to stdout

Nothing here touches a site.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]

from buildsmith.workflows.theme import build_site  # noqa: E402
from buildsmith.workflows.theme.build import TOKEN_SIGIL  # noqa: E402

__all__ = ["generate", "main"]

DEFAULT_SITE = "example"
DEFAULT_OUT = "docs/catalog.md"


def _token_keys(value: Any, found: set[str]) -> set[str]:
    """Every `@token` a spec references, read from the spec, not the output.

    Taken pre-resolution so the catalogue lists logical keys — which is what a
    reader can act on — rather than uuids, which are opaque and change per site.
    """
    if isinstance(value, dict):
        for item in value.values():
            _token_keys(item, found)
    elif isinstance(value, list):
        for item in value:
            _token_keys(item, found)
    elif isinstance(value, str) and value.startswith(TOKEN_SIGIL):
        found.add(value[len(TOKEN_SIGIL):])
    return found


def _tree(block: dict, depth: int = 0, lines: list[str] | None = None) -> list[str]:
    lines = lines if lines is not None else []
    element = block.get("element") or "(component)"
    label = ""
    if block.get("innerHTML"):
        text = str(block["innerHTML"])
        label = f' "{text[:40]}{"…" if len(text) > 40 else ""}"'
    if block.get("isRepeaterBlock"):
        label += "  [repeater]"
    lines.append(f"{'  ' * depth}<{element}>{label}")
    for child in block.get("children") or []:
        _tree(child, depth + 1, lines)
    return lines


def generate(site: str = DEFAULT_SITE, *, root: Path | None = None) -> str:
    """Render the catalogue. Deterministic — same inputs, same bytes."""
    base = root or ROOT
    site_dir = base / "sites" / site
    design = site_dir / "design"

    result = build_site(site_dir, site=site)
    manifest = json.loads((design / "tokens.json").read_text())
    tokens = manifest.get("tokens", {})

    out: list[str] = [
        f"# Component catalog — `{site}`",
        "",
        "**Generated by `buildsmith docs`. Do not edit.** The pre-commit hook regenerates",
        "this and refuses the commit if it differs, so hand edits are lost and a stale",
        "catalogue cannot be committed.",
        "",
        f"Built from `sites/{site}/design/`. Token references are shown as the logical",
        "keys the specs use; the uuids they resolve to are per-site and live in that",
        "site's applied token map.",
        "",
        "## Design tokens",
        "",
    ]

    if tokens:
        out += ["| key | type | value | dark | group |", "|---|---|---|---|---|"]
        for key in sorted(tokens):
            spec = tokens[key]
            out.append(
                f"| `{key}` | {spec.get('type', 'Color')} | `{spec.get('value', '')}` | "
                f"{'`' + spec['dark_value'] + '`' if spec.get('dark_value') else '—'} | "
                f"{spec.get('group', '—')} |"
            )
        out.append("")
        out += [
            f"{len(tokens)} token(s). Only `Color` and `Dimension` exist — anything else",
            "is a component prop plus one injected stylesheet (TRAP-004).",
            "",
        ]
    else:
        out += ["_No tokens defined._", ""]

    out += ["## Components", ""]
    component_dir = design / "components"
    specs = sorted(component_dir.glob("*.json")) if component_dir.is_dir() else []
    if not specs:
        out += ["_No components defined._", ""]
    for spec_path in specs:
        spec = json.loads(spec_path.read_text())
        component_id = spec.get("component_id") or spec_path.stem
        used = sorted(_token_keys(spec.get("root", {}), set()))

        out += [
            f"### `{component_id}` — {spec.get('name', component_id)}",
            "",
            "```",
            *_tree(spec.get("root", {})),
            "```",
            "",
        ]
        out.append(
            "**Tokens consumed:** " + (", ".join(f"`{k}`" for k in used) if used else "_none_")
        )
        out.append("")
        if spec.get("data_script"):
            out += ["Has a component data script.", ""]

    out += ["## Template", ""]
    if result.template:
        template = result.template
        out += [
            f"**{template.title}** — route `{template.route or '/'}`",
            "",
            "- `is_template`: yes",
            "- `template_group`: "
            + (f"`{template.template_group}`" if template.template_group else "_none_"),
            "",
        ]
        if template.template_group:
            out += [
                "Because it has a group, applying it needs developer_mode on the live site",
                "and writes fixture files onto the server (TRAP-006).",
                "",
            ]
    else:
        out += ["_No template._ This is a defect — every site build emits one.", ""]

    out += ["## Pages", ""]
    if result.pages:
        out += ["| title | route | dynamic |", "|---|---|---|"]
        for item in sorted(result.pages, key=lambda p: p.route):
            out.append(
                f"| {item.title} | `{item.route or '/'}` | "
                f"{'yes' if item.dynamic_route else 'no'} |"
            )
        out.append("")
    else:
        out += ["_No ordinary pages defined._", ""]

    return "\n".join(out).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--site", default=DEFAULT_SITE)
    parser.add_argument("--out", default=DEFAULT_OUT, help="'-' for stdout")
    parser.add_argument(
        "--check", action="store_true", help="do not write; fail if the file is stale"
    )
    args = parser.parse_args(argv)

    rendered = generate(args.site)

    if args.check:
        target = ROOT / args.out
        if not target.exists():
            print(
                f"ERROR: {args.out} does not exist. Run: buildsmith docs",
                file=sys.stderr,
            )
            return 1
        if target.read_text() != rendered:
            print(
                f"ERROR: {args.out} is stale — the design inputs or the generator changed "
                f"but the catalogue was not regenerated.\n"
                f"  Fix: buildsmith docs    (then stage {args.out})",
                file=sys.stderr,
            )
            return 1
        print(f"OK: {args.out} is current")
        return 0

    if args.out == "-":
        sys.stdout.write(rendered)
        return 0

    target = ROOT / args.out
    target.parent.mkdir(parents=True, exist_ok=True)
    changed = not target.exists() or target.read_text() != rendered
    target.write_text(rendered)
    print(f"{'wrote' if changed else 'unchanged'} {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
