#!/usr/bin/env python3
"""Generate a go-live plan for one site. Choreography only — it executes nothing.

A static checklist goes stale and gets skimmed. This one is generated from the
site's actual build, so it names the real routes, the real component payloads,
and only the steps that this site actually needs — a site with no shipped
template group is not told to enable developer_mode, so the steps that *are*
listed keep their weight.

Every live step is marked with who performs it. Buildsmith emits artifacts; the
operations project performs actions (ADR-002), and a plan that blurs that is how
someone ends up running a DNS change from a design repo.

    buildsmith golive --site example
    buildsmith golive --site example --out sites/example/go-live.md

Nothing here touches a site.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from buildsmith.primitives.template import (
    check_routes,
    prerequisites,
    requires_developer_mode,
    side_effects,
)
from buildsmith.workflows.theme import build_site

ROOT = Path(__file__).resolve().parents[2]

__all__ = ["generate", "main"]

OPS = "**operations project**"
HERE = "buildsmith"


def generate(site: str, *, root: Path | None = None) -> str:
    base = root or ROOT
    result = build_site(base / "sites" / site, site=site)

    pages = ([result.template] if result.template else []) + result.pages
    shipped = [p for p in pages if requires_developer_mode(p)]
    route_notes = check_routes(pages)

    out: list[str] = [
        f"# Go-live plan — `{site}`",
        "",
        "Generated by `buildsmith golive` from this site's actual build. Regenerate it",
        "rather than editing it; a hand-edited plan stops matching the payloads.",
        "",
        "**Buildsmith performs none of the live steps.** Each one below says who does.",
        "",
        "## What is being shipped",
        "",
        "| what | count |",
        "|---|---|",
    ]
    out += [f"| {k.replace('_', ' ')} | {v} |" for k, v in sorted(result.counts.items())]
    out.append("")

    if result.warnings:
        out += ["### Build warnings — resolve before going live", ""]
        out += [f"- {w}" for w in result.warnings]
        out.append("")

    needed = prerequisites(pages)
    if needed:
        out += ["## Prerequisites on the target site", "",
                "These are about the target, not the payloads, so no amount of validating",
                "the files will catch them. Each one was found by applying real payloads",
                "to a fresh site and watching them fail.", ""]
        out += [f"- [ ] {OPS}: {item}" for item in needed]
        out.append("")

    out += ["## Before anything", ""]
    out += [
        f"1. [ ] {OPS}: back up the site, and take a `Builder Snapshot`. Both.",
        f"2. [ ] {OPS}: confirm the scheduler and workers are running. `queue_action` "
        "with no worker locks documents permanently and the lock outlives the "
        "request (TRAP-009).",
        f"3. [ ] {OPS}: check `System Settings.time_zone` is set. Blank means "
        "timestamps are stored in IST, which has already caused a stale probe to "
        "be trusted (TRAP-008).",
        f"4. [ ] {HERE}: `buildsmith test` and `buildsmith validate --site {site}` are green.",
        "",
    ]

    out += ["## Tokens", ""]
    operations = len(result.token_plan) if result.token_plan else 0
    if operations:
        out += [
            f"1. [ ] {OPS}: apply `token-plan.json` — {operations} operation(s). "
            "It contains no deletes by construction; if you find yourself wanting "
            "one, stop and read TRAP-007.",
            f"2. [ ] {OPS}: read the token map back into `sites/{site}/"
            "tokens-applied.json`.",
            f"3. [ ] {HERE}: rebuild. Composition embeds each token's live value as "
            "the fallback in every reference, so components built before this are "
            "carrying stale literals.",
            "",
        ]
    else:
        out += ["Nothing to do — the site's tokens already match the manifest.", ""]

    out += ["## Components", ""]
    if result.components:
        out.append(
            f"1. [ ] {HERE}: for each payload, a clean `buildsmith simulate` run against a "
            "**current** state export. Exit 1 means it would collapse pages "
            "that work today (TRAP-001); exit 2 means nothing was checked — "
            "re-read the export, and never treat it as a pass."
        )
        for index, component in enumerate(result.components, start=2):
            out.append(
                f"{index}. [ ] {OPS}: apply `components/{component.component_id}.json`"
                + (
                    "  — **needs a ComponentSyncer pass across every consuming page**, "
                    "or its new nodes render nowhere"
                    if component.meta.get("requires_component_sync")
                    else ""
                )
            )
        out.append("")
    else:
        out += ["_No components in this build._", ""]

    out += ["## Template and pages", ""]
    step = 1
    if shipped:
        for template in shipped:
            out.append(
                f"{step}. [ ] {OPS}: enable `developer_mode` — required to save "
                f"`{template.title}`, and it must be turned off again afterwards."
            )
            step += 1
            for effect in side_effects(template):
                out.append(f"     - {effect}")
    for item in pages:
        out.append(
            f"{step}. [ ] {OPS}: apply `{item.title}` at route `/{item.route}`"
            + ("  _(template)_" if item.is_template else "")
        )
        step += 1
    if shipped:
        out.append(f"{step}. [ ] {OPS}: disable `developer_mode` again.")
        step += 1
    out.append("")

    if route_notes:
        out += ["### Route shadowing — one page at a time", ""]
        out += [f"- {note}" for note in route_notes]
        out += [
            "",
            "Build the dynamic page and confirm each record renders **before** "
            "retiring the static one. Retiring first 404s live URLs; renaming breaks "
            "inbound links (TRAP-010).",
            "",
        ]

    out += ["## After applying, before looking", ""]
    out += [
        f"1. [ ] {OPS}: clear the website cache — `bench --site <site> clear-website-cache`.",
        "     `find_page_with_path` is redis-cached for an hour, so a replaced page leaves",
        "     the route pointing at a docname that no longer exists and **every visitor",
        "     gets a 403** until the cache expires. Found by browsing a freshly applied",
        "     replica and being told 'Not Permitted' (TRAP-015).",
        "",
    ]

    out += ["## Cutover", ""]
    out += [
        f"1. [ ] {OPS}: DNS and reverse proxy, via its own playbooks and roles.",
        f"2. [ ] {OPS}: certificates issued and serving.",
        "3. [ ] verify **every** route over the public hostname, not just locally:",
        "",
    ]
    out += [f"   - [ ] `/{item.route}` — {item.title}" for item in pages if not item.is_template]
    out += [
        "",
        f"4. [ ] {HERE}: `buildsmith journal append --site {site} --tool golive` and attach "
        "the rendered build log to the ticket.",
        "",
        "## If it goes wrong",
        "",
        "Restore the snapshot taken in step 1. That is what it is for, and it is why",
        "the first step is not optional.",
        "",
    ]

    return "\n".join(out).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--site", required=True)
    parser.add_argument("--out", help="write here instead of stdout")
    args = parser.parse_args(argv)

    plan = generate(args.site)
    if args.out:
        Path(args.out).write_text(plan)
        print(f"wrote {args.out}")
    else:
        sys.stdout.write(plan)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
