#!/usr/bin/env python3
"""Generate `docs/builder-schema.md` by introspecting the pinned Builder.

Never hand-maintained. A hand-written schema reference is a description of what
someone believed Builder looked like on the day they wrote it, and this project
has already been bitten twice by exactly that kind of stale belief.

**Regenerating it is how a version bump gets reviewed.** Move the pin, run this,
read the diff. Fields that appeared, fields that vanished, a doctype that was
renamed — all of it shows up as a reviewable change rather than as a surprise
six weeks later.

**The staleness check does not need the sandbox.** The generated file records the
commit it was introspected from; `--check` compares that against
`sandbox/pins.env` and fails if they disagree. So moving the pin fails the commit
until someone regenerates — and regenerating requires a sandbox at the new pin,
which is the review actually happening.

    buildsmith schema            # needs the sandbox running
    buildsmith schema --check    # cheap; no sandbox needed

Nothing here touches a live site — only the local disposable sandbox.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUT = "docs/builder-schema.md"

__all__ = ["generate", "pinned_ref", "recorded_ref", "main"]

INTROSPECT = r"""
import json, frappe
frappe.init(site="sandbox.localhost"); frappe.connect()
out = {}
for name in sorted(frappe.get_all("DocType", filters={"module": "Builder"}, pluck="name")):
    meta = frappe.get_meta(name)
    out[name] = {
        "autoname": meta.autoname,
        "istable": bool(meta.istable),
        "fields": [
            {
                "fieldname": f.fieldname,
                "fieldtype": f.fieldtype,
                "options": (f.options or "").replace("\n", " | ") if f.fieldtype in
                           ("Select", "Link", "Table", "Table MultiSelect") else "",
                "reqd": bool(f.reqd),
                "unique": bool(f.unique),
                "read_only": bool(f.read_only),
                "default": f.default or "",
            }
            for f in meta.fields
            if f.fieldtype not in ("Section Break", "Column Break", "Tab Break", "HTML")
        ],
    }
print("SCHEMA:" + json.dumps(out))
"""


def pinned_ref() -> str:
    """The Builder commit `sandbox/pins.env` currently declares."""
    text = (ROOT / "sandbox" / "pins.env").read_text()
    match = re.search(r"^BUILDER_REF=(\S+)", text, re.M)
    if not match:
        raise SystemExit("sandbox/pins.env has no BUILDER_REF")
    return match.group(1)


def recorded_ref(path: Path) -> str | None:
    """The commit the committed schema doc says it was introspected from."""
    if not path.exists():
        return None
    match = re.search(r"^<!-- builder-ref: (\S+) -->", path.read_text(), re.M)
    return match.group(1) if match else None


def _introspect() -> dict:
    compose = ["docker", "compose", "-f", str(ROOT / "sandbox" / "docker-compose.yml")]
    running = subprocess.run(
        [*compose, "ps", "--status", "running", "--services"],
        capture_output=True, text=True,
    )
    if "bench" not in running.stdout.split():
        raise SystemExit(
            "the sandbox is not running, and the schema can only be read from it.\n"
            "  Start it with: buildsmith sandbox up"
        )

    completed = subprocess.run(
        [*compose, "exec", "-T", "bench", "bash", "-lc",
         "cd /home/frappe/frappe-bench/sites && /home/frappe/frappe-bench/env/bin/python -"],
        input=INTROSPECT, text=True, capture_output=True,
    )
    line = next((ln for ln in completed.stdout.splitlines() if ln.startswith("SCHEMA:")), None)
    if line is None:
        print(completed.stdout)
        print(completed.stderr, file=sys.stderr)
        raise SystemExit("introspection produced no schema")
    return json.loads(line[len("SCHEMA:"):])


def generate() -> str:
    schema = _introspect()
    ref = pinned_ref()

    lines = [
        f"<!-- builder-ref: {ref} -->",
        "# Builder schema reference",
        "",
        "**Generated by `buildsmith schema` from the pinned Builder. Do not edit.**",
        "",
        f"Introspected from commit `{ref}` running in the sandbox — not from",
        "documentation, and not from a version number. Builder's develop branch reports",
        "the same version string across more than a thousand commits, so the commit is",
        "the only meaningful identifier (ADR-004).",
        "",
        "Regenerating this is how a version bump gets reviewed: move the pin, rebuild the",
        "sandbox, run `buildsmith schema`, and read the diff. `--check` fails the commit",
        "while the pin and this file disagree.",
        "",
        f"{len(schema)} doctype(s) in the Builder module.",
        "",
    ]

    for name in sorted(schema):
        info = schema[name]
        lines.append(f"## {name}")
        lines.append("")
        details = []
        if info.get("autoname"):
            details.append(f"`autoname: {info['autoname']}`")
        if info.get("istable"):
            details.append("child table")
        if details:
            lines += [" · ".join(details), ""]

        fields = info.get("fields") or []
        if not fields:
            lines += ["_No data fields._", ""]
            continue

        lines += ["| field | type | options | flags |", "|---|---|---|---|"]
        for field in fields:
            # Select options are pipe-separated, and an unescaped pipe silently
            # splits the row into extra columns.
            options = field["options"].replace("|", "\\|")
            flags = [
                flag
                for flag, on in (
                    ("required", field["reqd"]),
                    ("unique", field["unique"]),
                    ("read-only", field["read_only"]),
                )
                if on
            ]
            if field["default"]:
                flags.append(f"default `{field['default']}`")
            lines.append(
                f"| `{field['fieldname']}` | {field['fieldtype']} | "
                f"{('`' + options + '`') if options else '—'} | "
                f"{', '.join(flags) if flags else '—'} |"
            )
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--out", default=DEFAULT_OUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    target = ROOT / args.out

    if args.check:
        pinned, recorded = pinned_ref(), recorded_ref(target)
        if recorded is None:
            print(
                f"ERROR: {args.out} is missing or records no Builder commit.\n"
                "  Fix: start the sandbox and run buildsmith schema",
                file=sys.stderr,
            )
            return 1
        if recorded != pinned:
            print(
                f"ERROR: {args.out} was introspected from {recorded}, but the pin is now "
                f"{pinned}.\n"
                "  The schema reference describes a Builder this project no longer targets.\n"
                "  Fix: buildsmith sandbox up && buildsmith schema    (then read the\n"
                "  diff — that is\n"
                "  the version-bump review)",
                file=sys.stderr,
            )
            return 1
        print(f"OK: {args.out} matches the pin ({pinned[:12]})")
        return 0

    rendered = generate()
    target.parent.mkdir(parents=True, exist_ok=True)
    changed = not target.exists() or target.read_text() != rendered
    target.write_text(rendered)
    print(f"{'wrote' if changed else 'unchanged'} {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
